# To add a service, copy and paste one of the items in this list and edit the contents.
# To delete a service, remove the whole bullet point.
# To change the icon that shows, find a new icon at https://fontawesome.com/v4/icons/ and copy the 
#   tag that appears under the icon.  For example, https://fontawesome.com/v4/icon/address-book-o
#   would be 'fa-address-book-o'

- service: Line Editing
  fa-icon: fa-list
  description: >
    Worried that your writing doesn't quite capture the tone or impact you're aiming for? Line editing can help! A line edit looks at each sentence to enhance clarity, style, and flow, ensuring your voice comes through clearly and powerfully. This service is perfect if you want your writing to resonate with readers without losing your unique personality! 
  
    This service starts at .025 cents/word.

- service: Copyediting
  fa-icon: fa-file-text-o 
  description: >
    Worried about errors or inconsistencies in your work that could distract your audience? Copyediting can help by addressing grammar, punctuation, and style consistency so your message is clean, polished, and professional. Copyediting can give you confidence that your writing is accurate and ready for your readers! 
  
    This service starts at 2 cents/word.

- service: Proofreading
  fa-icon: fa-pencil-square-o
  description: >
    Ready to publish but want reassurance that there are no overlooked mistakes? Proofreading can provide that final quality check! My proofreading service combs through your text to catch any remaining typos, punctuation errors, and minor inconsistencies, giving you a distraction-free finish that lets your content shine! 
  
    This service starts at 1 cent/word.

- service: Course Content Review
  fa-icon: fa-graduation-cap
  description: >
    Worried that your course content isn't organized? Worried that distracting errors will make your students question your credibility? My course content review focuses on structuring your material for easy comprehension, ensuring your course is clear and supportive for learners. This service helps you deliver content that's not only educational but also engaging and effective! 
    
    Cost is dependent on the length of the course and how much input you want to receive.

 

